---
# Playbook: Setup SSH Keys
# Deploy SSH public key ke semua server
#
# Usage:
#   ansible-playbook setup-ssh.yml --ask-vault-pass            # Run dengan vault password
#   ansible-playbook setup-ssh.yml --vault-password-file .vault_pass  # Pakai password file
#   ansible-playbook setup-ssh.yml --limit vm1 --ask-vault-pass       # Hanya vm1
#   ansible-playbook setup-ssh.yml --check --ask-vault-pass           # Dry run

- name: Setup SSH Keys on All Servers
  hosts: all_servers
  become: yes
  gather_facts: yes

  vars_files:
    - group_vars/all.yml
    - secrets.yml

  # Use password from secrets.yml for initial setup
  # vars:
  #   ansible_ssh_pass: "{{ ansible_ssh_pass | default(omit) }}"
  #   ansible_become_pass: "{{ ansible_become_pass | default(omit) }}"

  tasks:
    - name: Display target server info
      debug:
        msg: "🖥️  Configuring {{ inventory_hostname }} ({{ ansible_host }}) - User: {{ ansible_user }}"
      tags: always

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'
      tags: ssh

    - name: Backup existing authorized_keys
      copy:
        src: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys.backup.{{ ansible_date_time.date }}"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      ignore_errors: yes
      when: backup_authorized_keys | default(true)
      tags: ssh

    # Method 1: Using ssh_public_key from secrets.yml
    - name: Add SSH public key from secrets
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_public_key }}"
        exclusive: no
        comment: "Added by Ansible on {{ ansible_date_time.date }}"
      when: ssh_public_key is defined
      tags: ssh

    # Method 2: Using local public key file (alternative)
    - name: Add SSH public key from local file
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', ssh_public_key_file) }}"
        exclusive: no
      when: ssh_public_key is not defined and ssh_public_key_file is defined
      tags: ssh

    - name: Ensure correct permissions on authorized_keys
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      tags: ssh

    - name: Verify SSH service is running
      systemd:
        name: ssh
        state: started
        enabled: yes
      tags: ssh

    - name: Display success message
      debug:
        msg: |
          ✅ SSH key deployed successfully to {{ inventory_hostname }}
          
          Test dengan: ssh -i ~/.ssh/id_work {{ ansible_user }}@{{ ansible_host }}
      tags: always
